Transparent status bar and navbar
fumiama/copymanga pull request #71
Opened 2024-05-20 14:49 UTC by DtHnAme

支持高版本 Android 沉浸式状态栏和导航栏

2024-05-20 14:57 UTC, DtHnAme commented
安卓13 准确说应该是从浅灰色遮罩 变为透明

2024-05-20 15:00 UTC, fumiama commented
其实我之前是加过相关代码的，但是因为在显示上有其他问题所以取消了。另外浅灰遮罩我并不认为有什么问题，因为可以增加层次感，而且也是安卓官方的设计。不过还是感谢你的想法。

https://github.com/fumiama/copymanga/blob/36852a52dd8d635fb9179c646a0254d84cf5d23e/app/src/main/java/top/fumiama/copymanga/MainActivity.kt#L210-L228

2024-05-20 15:05 UTC, DtHnAme commented
好的 但感觉在较新安卓版本中还是纯色透明更有沉浸感

2024-05-20 15:17 UTC, fumiama commented
关键目前toolbar并未做成collapse，所以就算是完全沉浸，其实也就是换了个颜色😂。不过你可以做一个开关，不要新增xml文件，一切都在代码中设置，然后在设置的“通用”条目里新增一项，启动时读取并应用到Main和Login。具体代码可以参考我上面发的。

2024-05-20 16:27 UTC, DtHnAme commented
现已支持设置控制

2024-05-21 03:41 UTC, fumiama requested changes

2024-05-21 03:41 UTC, fumiama commented on app/src/main/java/top/fumiama/copymanga/LoginActivity.kt
> +            if (contains("settings_cat_general_sw_enable_transparent_systembar")) {
不用contain吧，下面设了默认值。

2024-05-21 03:41 UTC, fumiama commented on app/src/main/java/top/fumiama/copymanga/MainActivity.kt
> +            if (contains("settings_cat_general_sw_enable_transparent_systembar")) {
同

2024-05-21 03:41 UTC, fumiama commented on app/src/main/java/top/fumiama/copymanga/ui/vm/ViewMangaActivity.kt
> +        if (settingsPref?.getBoolean("settings_cat_general_sw_enable_transparent_systembar", false) == true) {
ViewManga别加了，默认全屏的。

2024-05-21 03:41 UTC, fumiama commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
这个有必要吗？

2024-05-21 03:43 UTC, DtHnAme commented on app/src/main/java/top/fumiama/copymanga/ui/vm/ViewMangaActivity.kt
> +        if (settingsPref?.getBoolean("settings_cat_general_sw_enable_transparent_systembar", false) == true) {
不加这个在全面屏设备下 状态栏默认黑边

2024-05-21 03:43 UTC, DtHnAme commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
这个是为了去掉默认的灰色遮罩

2024-05-21 03:44 UTC, DtHnAme commented on app/src/main/java/top/fumiama/copymanga/LoginActivity.kt
> +            if (contains("settings_cat_general_sw_enable_transparent_systembar")) {
这个 确实有点多余了我改下

2024-05-21 03:52 UTC, fumiama commented on app/src/main/java/top/fumiama/copymanga/ui/vm/ViewMangaActivity.kt
> +        if (settingsPref?.getBoolean("settings_cat_general_sw_enable_transparent_systembar", false) == true) {
ok

2024-05-21 03:53 UTC, fumiama commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
能不能改成代码实现？这个用开关顾及不到呀。

2024-05-21 03:55 UTC, DtHnAme commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
去除View本身的灰色遮罩 不影响状态栏的灰色遮罩

2024-05-21 03:58 UTC, fumiama commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
既然不影响状态栏，那这个遮罩是管啥的

2024-05-21 04:04 UTC, DtHnAme commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
谷歌默认给NavigationView 加了一层灰色的遮罩 在沉浸模式下 状态栏是透明的 但是NavigationView自己有一层需要去掉 而正常模式下 因为状态栏本身有遮罩 去掉这一层也不影响

2024-05-21 04:07 UTC, fumiama commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
你说navigation view，那导航栏呢，这个加上之后导航栏的遮罩是不是就没了

2024-05-21 04:09 UTC, DtHnAme commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
刚试了 都不影响

2024-05-21 04:11 UTC, fumiama commented on app/src/main/res/layout/activity_main.xml
> +        app:insetForeground="@android:color/transparent"
ok

2024-05-21 04:12 UTC, fumiama approved these changes

2024-05-21 04:12 UTC, merged